[:html
    [:head 
        [:title "Wiseyak WiseMD - Capture a complete patient health story"]
        [:link {:rel "stylesheet" :type "text/css" :href "styles/normalize.css"}]
        [:link {:rel "stylesheet" :type "text/css" :href "styles/skeleton.css"}]
        [:link {:rel "stylesheet" :type "text/css" :href "styles/main.css"}]
        [:link {:rel "stylesheet" :type "text/css" :href "styles/css.css"}]]
    [:body 
        [:div {:class "navbar"}
            [:div {:class "container"}
                [:a {:href "http://wiseyak.com"}
                    [:img {:class "logo" :src "images/wiseyak-logo.png" :alt "Wiseyak"}]]
                [:div {:class "wise-desktop"}
                    [:ul {:class "navbar-list"}
                        [:li {:class "navbar-item"}
                            [:a {:class "navbar-link" :href "http://wiseyak.com/about"} "About"]]
                        [:li {:class "navbar-item"}
                            [:a {:class "navbar-link" :href "http://wiseyak.com/contact"} "Contact"]]]]]]
        [:div {:class "container"}
            [:div {:class "wise-hero"}
                [:div {:class "row"}
                    [:div {:class "ten columns offset-by-one" :style "margin-top: 30px; margin-bottom: 30px;"}
                        [:img {:class "u-max-full-width" :src "images/wiseyak-black-circle.png"}]]]
                [:div {:class "row"}
                    [:div {:class "ten columns offset-by-one"}
                        [:h1 "We help capture a complete health story"]
                        [:p [:strong {:style "color:blue;"} "Wise"]
                            [:strong "MD"]
                            " is an on-boarding tool to capture a complete patient health story for physicians and clinicians"
                            " and make meaningful use of patient generated health data and information."]]]]
            [:div {:class "row wise-section"}
                [:div {:class "five columns offset-by-one"}
                    [:h2 "Less Paperwork"]
                    [:p "Engage patients to gather information before their appointment"
                        " through contextual follow-up questionnaire."]
                    [:a {:class "wise-primary-link"} "Learn More"]]
                [:div {:class "wise-desktop six columns"}
                    [:img {:src "images/wiseyak-note.png" :height "200"}]]]
            [:div {:class "row wise-section"}
                [:div {:class "five columns"}
                    [:img {:src "images/wiseyak-integrate.png" :height "200"}]]
                [:div {:class "five columns offset-by-one"}
                    [:h2 "Integrate Patient Data"]
                    [:p "We make sure patient generated data from personal and IoT medical devices "
                        "can be easily integrated into their story."]
                    [:a {:class "wise-primary-link"} "Learn More"]]]
            [:div {:class "row wise-section"}
                [:div {:class "five columns offset-by-one"}
                    [:h2 "Interoperability"]
                    [:p "We make sure data generated by our tool is fully compatible with "
                        "existing HL7 and mHealth standards."]
                    [:a {:class "wise-primary-link"} "Learn More"]]
                [:div {:class "wise-desktop six columns"}
                    [:img {:src "images/wiseyak-note.png" :height "200"}]]]]
                    
        [:div {:class "footer"}
            [:div {:class "container"}
                [:div {:class "row newsletter-signup"}
                    [:div {:class "four columns"}
                        [:h6 "Be the first to know"]
                        [:span "Keep up-to-date with our latest developments by signing up"]]
                    [:div {:id "mc_embed_signup"}
                        [:div 
                            [:div {:class "five columns offset-by-one"}
                                [:input {:name "EMAIL" :class "u-full-width" :placeholder "Email Address" :type "email"}]]
                            [:div {:class "two columns"}
                                [:input {:class "button-primary" :value "Sign up" :type "submit"}]]]]]
                [:div {:class "row"}
                        [:div {:class "three columns"}
                            [:h6 "Company"]
                            [:a {:href "http://wiseyak.com/about-wisemd"} "About WiseMD"]
                            [:a {:href "http://wiseyak.com/about"} "About us"]]
                        [:div {:class "three columns"}
                            [:h6 "Contact"]
                            [:a {:href "http://wiseyak.com/contact"} "Contact us"]
                            [:span "Wiseyak, Inc."]
                            [:span "3600 136th Pl SE. #300"]
                            [:span "Bellevue, WA 98006"]]
                        [:div {:class "three columns"}
                            [:span "© Wiseyak, Inc."]]
                        [:div {:class "three columns"}
                            [:span "Bizspark Member"]]]]]]]